FROM nvcr.io/nvidia/pytorch:19.04-py3

RUN apt update -y && \
    apt install -y python3-pip software-properties-common wget ffmpeg

RUN mkdir -p /root/.torch/models

RUN mkdir -p /data/models

WORKDIR /data

COPY ./requirements.txt ./requirements.server.txt ./

ENV PIP_NO_CACHE_DIR=1

RUN pip install -r ./requirements.server.txt

COPY ./deoldify ./deoldify

COPY ./app.py ./app_utils.py ./

EXPOSE 5000

CMD python3 -u ./app.py

